rvm:
  - 2.2.2
notifications:
  email: false
  slack:
    secure: idWXWKmV7SchA8SG3F4qVp/Ym/UvcxgU3RE0eGPhAzCM8oxqlj672TjMplNSVcR+nfZ52Ldwr5vJOjGFrJ5j8qrbY7p9EWLPPxQV2YJqXWc+VDCetyKB55DLW01zBY7RQugSsz/UUGlcSwVGWP+dsq9vC4z2JPaZ4xgyHkEPz2f9ve3jcziWbC6dCU5P40FgwWrMquD2iRe+Y+4Sy20RCgIVGgGMB1DGLuWzONI1vZI8zdOSGDM2S3ACTigLfc6eKiF0Z/JITtmVgqLHGRZ51FMiawhKGcW36d3CpNvyE28GMaKGa6CTe4P9u9MuCG/Qs8wlyj2pK15+ywzAc7ek0uBvSZ+/2TdOQKoqWA/Cz8J8SBjwxewp0zwKkNfXF2sg9szl6G1cGOUBjPH9cUp0izDLd8m9gKoWmINe/ynmekCo/UhCPM/nhv9RWMkQTivkdguYBiG+bXNltTc1uDQuJEHg7GefoLeuVRKmM3RQRHpWJs1NMZkwtiLyzcpA5uEJmMbJqrqozmdFtjDvYIJ4K/Fg377PDif2b4KnaDkj4sdb9HB2FaSAPvaAbZ2nJRzFgSKbFFM+JKeywSPpkv8YS7AIn+HPPd24nwHTHy70Q+JnRExsn89wnNz7E7icNXHywXtSFRIsNEgJzpEEBpYu6V6DkE9ibF4Ngc56O8LeRQo=
deploy:
  provider: heroku
  app:
    master: pic
  on:
    branch: master
  api_key:
    secure: l7ycOaqsFDcpnoKPA/f/KM5y2K/oWb81cLw6OXjkEF+bh3pg8gXPa2wog2EYzuD/jMCS5jFpaPBsjG8UQFVRCxPRk3kHU2cNLiEK4OSZ+cR+ZdkZ2Vu9xoNyN/vPo8ioQ1WpmlAeJgTVdrGSguWBzlEFTVtk51szs3YEqTsvR2tlrVUziZsLMBDivGK8uWZV7Ha96QyiCrGkzZ2tQ3hgv6mwcXKDbyziFR5/A6ri3EJriQoru+3BpsOaPdqgLQ9eugYMxxi2l13Q22QhFGIrpVR6LK9Q0XTxY+G8XTvU0KSz+ezi0qwm9v3+cSFqfttUhwmku6BWyCfLibEoPJgfUSaJK+SzZMqj4wnm6XQVgn+WLQidwFD2yNZ6s7+p/JMeH+gRI6zSEConNn5zhxRdWcz5wZ5NmSgdIV7ZAw4miuTe4Jfx+AgUV+CrYsBxH1Ji0NQQykLWYWedh445oTqUnDqAxTeNYlRYuNXuyjx6sK6YNPrSmmx1uVzG+iRlfIooIjGE2lV05OKkvBrhl/rlkmJhoufoV78+feV4+YsQ0akehAYxr/AYeXFT2KRj1CbXzWrw51EtrSHXAQPhktfZBwv3fuVTJqHNV7cUyqKDr4swNN7DVfCbKsYkVAztkMwHFbKMmQP4QN0L5Ap4ImD8VYfWXUcddBYBM5nfXs4PuuY=
