language: python
branches:
  except:
  - gh-pages
  only:
  - csv
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- "./python/prebuild.sh"
env:
  global:
  - GH_REPO="mgiraldo/pic"
  - secure: kCXxEHi6t9mnyXKjBVLMnmWh2TEICp+z/CC1sRU0Yf7Cr54880KJiZu3PrfZVu99ZSw8xvd44JkJOe4O59yss61gyCB9JrsT66VNyPqqtxbIcVZdBJvDbdO4i9YUV2acddKdR2+7d8SjpYZhVFGgSviccMZkcJomeIBg9uaW7b7VyFzlTWGEWx3VVu32ah+GK+rJ48SuB8YhZWUqWaYxEIMpSSym8P9FONCNuKbspOpfhTWKv5TQoYsvPOXPp+SJX5Iwh7f89Fd17gaAEAQHXJLf+1gvDy4FQSF7DX7s6ytf9dyaivMIXYBEy+r/zOjtgn/V3/gkCuGVqP7UNMjERzUZJblUgtBhMDv841DcMiC8ZC+b1z1CCqvSUCVpClRwHVDKmv9XyVxfuEM1F46cS4k+hIeGUTtugkamhEBCdwl4s9Rdr+dUQXEhioO8cZMnGENGByGr+dqxV6qQSqPJ3KW+4eRFyQMhx81GJGVkF4qDhx15euJRzxnBw6RfpYQrxiKrxKq6waxVbIxsbaJ1I6htCSxRllZDSgOZ42S1vd5IGPYYpF1ecFnLi7TGZglmSKPX/4MHHsIPVXU9QqLbBTIigHQqRtnIJxHCqn9YXtXW6EnE2CeIgYgwF0eP0PegGmxuM/t3EvoskPHpT9CSOcVBPoCMrulf9rsVK4DHK6U=
notifications:
  slack:
    secure: Rs3A9V+GqTvn8v0tClp8YWDBOrt60SN0SotlwNyxbB/0iDuw3niEN/ElIni71X0D92yOpSEcN/ZDWRMYNiOR6NClyiJhinc6/4u/hGpn9PY5Ix+jiBeigQf+OMcYnFT+j/owly8Ph8yRwY5uQpVYGeWwXK3kEVhVfbcMmh/hGMg8bEpoRELkRp6AGaDmjSIqa6yqtjiNMNSu2ciqPGmWv44WtGN5g+wEWzRYgk+1io7v80S0y8/9H9XFyG0daq8AMlaSxm+0M6wWQuQwCG6e1rSbYFc8k12H5wEy+XhZimqtgBdZWxguXXgZVgQc4ExXEG2Z+klCophYbdYMwVMkqYESFY/MLTurpVH5oOWcEPCYzyP7uzZ1jDfERQXkwQZfjpAzDdls+lEEGBNCE7j5/enC7zHW6Iwxj57VZt3UPTd0Wl8cKoVogG6KzXN06nDQIom+lJjY5VZxhNliuZ4CEZJFSVGfKpfu3XyQsP0pSBnYNZFxtwFWM98IEjGyIDE366U8cwe8grbrsZNxYSt0FN+AZmZB2IK7TMvhktx+RcmMlQkWIaRWJhzVqo9MycKo99MELLFJoBk2144lREIgo1mXSRFFKDRycjub4iwoOsL5fAUc7LKIJ23b4ywgb0T5ZuCl+fWgtKD98/wybMjf05ciZ3FlgjA8aMcx2A/N7Fg=
