language: python
branches:
  except:
  - gh-pages
  only:
  - csv
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- "./python/prebuild.sh"
env:
  global:
  - GH_REPO="mgiraldo/pic"
  - secure: Lfq2HNusWLrFEQTArHfv4A095wzYfB3/F36S5ozgCBGZtURqtQwNPsVcUkTKoiALYbmJlrJq6epcQf2490VlMog6jqiRKAysSYMqyVInkkXznn75AIwMU1cgXvq4rEAEb96KVfLP4VNor5cW5DZJ0xhMP+zHFk5cMRFSShOmTB7w6Q0wQp+nX7gbq+FZTM9KObS8ghTYGRqAXUPRcIg0e1MuroUFUfpS1Jf8/BKDR1csfzayb6EsLXvEeU5riZReHuH933Y6wkZZm0kNtrAc1f9sVP8T9iDuakfdNl5R0XrUDkrWc0S7/yC0yQPVjZ53Dt1lYJ69HqF1FqQe11VPeccD0mSlE2rG6KrC75zLUIzBmyhuHdAWxnTfc55bOouNX+3oJVPb6lp+bGXeHKiAudCHBMZvHfQz6725cu9wkll5AbX4hQPPtM18qts2eIFTysHUjVaYyvNMZYQebKGoDrYHfsbUCyje7+uofIi5Re090ZhwASgA08vreZUSyAIoGA6Awnk81KRmekjkfYWXiVOuanqQBdUmLuuBrtwldEj/xNx48uEDUQ0X0uq9qb+bEZ/X7fZ8RWQhbyBsr6gzv1Otuu2UPIE2t/RQKiaQ20wsAzF5rYJUgChp0NLrOXRddb2bxTDhyCgTEnOx5A2ROduBpX5qbyQ7Dyl96NvaGzY=
  - secure: ZyFiyALbkY0JvgN5BXiZYp7fb9CBA8r+Esik6IHLPOv/5UNi4x/6UVLyqJvJlTcRL3zpSQaJ6hrZIUcp05/VJCyvGC0FMO3PfACwRT2L/prHzX8tAWLesgGBt6JNqfWK+CWrewsxxySBkwIxTZq5fe53EGfJb8v4ByLKwX6ItoTnb8CdFeAcCFJ9etIBSRgn+I8rK4RZjWmIUOdLxsQbbwS4K1RvkVCDbPiIm+mLwxV566ztUqPxX9+yOQ2pUg9eEAf5+MeDbqnA7FnGibLIteeu3iXGE57REVhMAuCyZeJ+/0XGYVgGopxdyBBz5zq+HcqoAui7aY+6hodYczrQs7tWd4aUGHlz8bsFs2orFsq2i1hqfNumeeVbNCkprBm3WN32GVwwiS7N3qVlyW2fX1Fa2LGoDWHhD6xNZT92pQF86rW1pLBIJmwnO1QCpebF2XeA3HH1yQF1m8Nc7wKuTJ8nLr/omK66tMuOwi8xRbljLrj+dpMRD5smESTTZqnw9kSMU5GPTm9HslfTg2dAoAaZDi5GmqIiZ4qpaeKxZbUz8h05wqWPBQ3aXOnjrvIdp6e0nLHvT+ZBGjCUVso1VMRdC0ItNq/eXBLwBEeg083ZVK2My+bS9GqYe+GBFsPZ/khH2ZEIWm4rW8kl4V25gQOtBKmUfz03dx59UDEDHys=
notifications:
  slack:
    secure: Rs3A9V+GqTvn8v0tClp8YWDBOrt60SN0SotlwNyxbB/0iDuw3niEN/ElIni71X0D92yOpSEcN/ZDWRMYNiOR6NClyiJhinc6/4u/hGpn9PY5Ix+jiBeigQf+OMcYnFT+j/owly8Ph8yRwY5uQpVYGeWwXK3kEVhVfbcMmh/hGMg8bEpoRELkRp6AGaDmjSIqa6yqtjiNMNSu2ciqPGmWv44WtGN5g+wEWzRYgk+1io7v80S0y8/9H9XFyG0daq8AMlaSxm+0M6wWQuQwCG6e1rSbYFc8k12H5wEy+XhZimqtgBdZWxguXXgZVgQc4ExXEG2Z+klCophYbdYMwVMkqYESFY/MLTurpVH5oOWcEPCYzyP7uzZ1jDfERQXkwQZfjpAzDdls+lEEGBNCE7j5/enC7zHW6Iwxj57VZt3UPTd0Wl8cKoVogG6KzXN06nDQIom+lJjY5VZxhNliuZ4CEZJFSVGfKpfu3XyQsP0pSBnYNZFxtwFWM98IEjGyIDE366U8cwe8grbrsZNxYSt0FN+AZmZB2IK7TMvhktx+RcmMlQkWIaRWJhzVqo9MycKo99MELLFJoBk2144lREIgo1mXSRFFKDRycjub4iwoOsL5fAUc7LKIJ23b4ywgb0T5ZuCl+fWgtKD98/wybMjf05ciZ3FlgjA8aMcx2A/N7Fg=
