language: python
branches:
  except:
  - gh-pages
  only:
  - csv
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- "./python/prebuild.sh"
env:
  global:
  - GH_REPO="mgiraldo/pic"
  - secure: Wy0kR4eiUldb+0O0QjPo191bMEOJo0512Bdpnpl4ShbZ1es1sJEFdpHz1L+XJlw4HuZ8U8rVySCbhEISbVg1Rn4Ey2q9403S8sCWfcj8sYqUh4IaxWLDMmV4U9+o+myYegjPE+qGGkMu1+jshcBNFaXLH7Q1bzNxqHrkYpNjWNLtQQ0W9mqgn0Qb4PaViA0dY/3Ksj2xMpVke/xAotVjWA0iTMokVAieybaez5cVwb58/Qh/UM3lVCHvZpGI5x9+iy9NILY1Y/dLCpcbkX2U2TP9GrMAdLRIut0HHLMcTLRW18AkqW4ijnyeRYMuiiJJ5S6lUzVNqBvJTqbrnLJ6T2F2R1BKtznGaugqCvrOSwiOBQq2QuxmGHNfr7X9gsvdEPyitffAI2AxF73tkshnk6HM7ZNF7JAc6pBXTlQ8Zca6rOHpvs/CCIsgZM0ay4feTtTkeT8mY6bDrEynffe5JJ6LsfaQBrd0YDr24o23+ofNutcSC6XpiJNHneHrOoBEibBSNt5LKdsRI7aOTMiD3Sel5z4I0zAdMQ7K+njqzvJlbdbuJ/QFK4k2Ia9RRkgShSO0gOQg3jm64A7NPmI4S2KY5YGXjwQw4bsJidQdOpumzlB2xABGJaj4GubTMKgnDm7AeLY2J+g2px8UA78gLQ4D/pbvJ7RouZvSAg5TNgY=
notifications:
  slack:
    secure: Rs3A9V+GqTvn8v0tClp8YWDBOrt60SN0SotlwNyxbB/0iDuw3niEN/ElIni71X0D92yOpSEcN/ZDWRMYNiOR6NClyiJhinc6/4u/hGpn9PY5Ix+jiBeigQf+OMcYnFT+j/owly8Ph8yRwY5uQpVYGeWwXK3kEVhVfbcMmh/hGMg8bEpoRELkRp6AGaDmjSIqa6yqtjiNMNSu2ciqPGmWv44WtGN5g+wEWzRYgk+1io7v80S0y8/9H9XFyG0daq8AMlaSxm+0M6wWQuQwCG6e1rSbYFc8k12H5wEy+XhZimqtgBdZWxguXXgZVgQc4ExXEG2Z+klCophYbdYMwVMkqYESFY/MLTurpVH5oOWcEPCYzyP7uzZ1jDfERQXkwQZfjpAzDdls+lEEGBNCE7j5/enC7zHW6Iwxj57VZt3UPTd0Wl8cKoVogG6KzXN06nDQIom+lJjY5VZxhNliuZ4CEZJFSVGfKpfu3XyQsP0pSBnYNZFxtwFWM98IEjGyIDE366U8cwe8grbrsZNxYSt0FN+AZmZB2IK7TMvhktx+RcmMlQkWIaRWJhzVqo9MycKo99MELLFJoBk2144lREIgo1mXSRFFKDRycjub4iwoOsL5fAUc7LKIJ23b4ywgb0T5ZuCl+fWgtKD98/wybMjf05ciZ3FlgjA8aMcx2A/N7Fg=
